version: '3'

services:
  mariadb:
    container_name: "cred-db"
    image: "mariadb"
    ports: # mysql ports item
      - "${DB_PORT}:3306" # mysql ports value
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_PREFIX: "${DB_PREFIX}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped